### ISSUE TITLE
Long time for starting app or console

### ISSUE THREAD

**Issue by yurgon** [stephenmoloney/arc_ovh#1]
Hey
After I added arc_ovh to my Phoenix app my application get a long time for starting command:

mix phx.server
iex -S mix

I assume this is due to the fact that the module each time it receives a token for authorization on the side of OVH
Maybe there is a way to specify this token in config file for Openstack Swift ?
Because I can generate once the Admin panel on OVH, see sreenshot http://joxi.ru/Vrw0bwTKJ4K8mX

Thx

**Comment by stephenmoloney** [comment]
Hi Yurgon,

Yes, each time the application starts, the token is generated by `openstex_adapters_ovh` on application startup only -- basically waiting for OVH to generate the token. In theory, I suppose the application should only start on rare occasions if it was in production so it shouldn't be too big a problem. However, I still agree with you that this slows down application startup and it should be optional rather than the default situation.

This [function call](https://github.com/stephenmoloney/openstex_adapters_ovh/blob/f1952370a5d51928268eedbf14c478faa6478a70/lib/openstex/ovh/keystone/utils.ex#L54
) is what we are talking about.

The alternative would be to get the  `x-auth-token` by using the openstack:
- `username`
- `password`
- `authurl`
- `tenant`

I'm not sure if this would be faster but it is possible. Apart from being faster, this is actually badly needed anyways to avoid regenerating the `x-auth-token` for the ovh openstack instance on every application startup. The ability to separate into users with their own credentials is needed. This has been something I've wanted to do for a while but I had about a 6 month break from programming up until 2 weeks ago. So I am only getting time now again for various programming tasks.

Anyways, about using the `Generate an Openstack Token` option. This is not plausible because it generates the `x-auth-token` -- that token will change periodically and so it is not a good idea to put it into the `config.exs`, it will simply have changed too often. But it should be allowing for the following options:
- `username`
- `password`
- `authurl`
- `tenant`
in the config.exs. This then should default to a situation where the auth token is gotten using those credentials only.

So finally, the question is `How to implement this?`

I think the best way is probably a new adapter called `openstex_adapters_default`. Then this adapter should be able to authenticate a user for any generic openstack cloud. I'm not 100% sure about this but I think it should be feasible - although I can't tell until I start writing an adapter like that. Then another package called `arc_swift` can integrate the adapter into it directly if my logic is right.

I'm just not sure right now when I will get time..... maybe in a few days/weeks

 :thinking:

**Comment by stephenmoloney** [comment]
Adding more information here as to a more exact description of why there is a delay for app startup....

Reason it is slow is this line:

https://github.com/stephenmoloney/openstex_adapters_ovh/blob/f1952370a5d51928268eedbf14c478faa6478a70/lib/openstex/ovh/keystone/utils.ex#L5

Reducing the delay leads to other problems because my tests when developing the adapter showed that there was a significant delay of sometimes > 10seconds when regenerating the credentials for OVH.

This doesn't change anything for the solution, it is still as follows:

I think the best way is probably a new adapter called openstex_adapters_default. Then this adapter should be able to authenticate a user for any generic openstack cloud. I'm not 100% sure about this but I think it should be feasible - although I can't tell until I start writing an adapter like that. Then another package called arc_swift can integrate the adapter into it directly if my logic is right.

**Comment by yurgon** [comment]
sometime I get error:

```
** (Mix) Could not start application arc_ovh: ArcOvh.Application.start(:normal, []) returned an error: shutdown: failed to start child: ArcOvh.Client.Cloudstorage
    ** (EXIT) shutdown: failed to start child: Openstex.Adapters.Ovh.Config
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, %HTTPipe.Conn{adapter: HTTPipe.Adapters.Hackney, adapter_options: [timeout: 10000, recv_timeout: 30000], error: %HTTPipe.Adapters.Hackney.RequestError{message: "Hackney encountered an error while attempting to communicate with\nthe server. The reason given was:\n\nclosed\n"}, options: %{defer_body_processing: false}, request: %HTTPipe.Request{body: nil, headers: %{"Content-Type" => "application/json; charset=utf-8", "X-Auth-Token" => "CODE"}, http_version: "1.1", method: :get, params: %{}, url: "https://storage.gra1.cloud.ovh.net/v1/AUTH_CODE"}, response: nil, status: :failed}}
                (openstex_adapters_ovh) lib/openstex/ovh/config/config.ex:156: Openstex.Adapters.Ovh.Config.get_account_temp_url/3
                (openstex_adapters_ovh) lib/openstex/ovh/config/config.ex:92: Openstex.Adapters.Ovh.Config.swift_config/3
                (openstex_adapters_ovh) lib/openstex/ovh/config/config.ex:44: Openstex.Adapters.Ovh.Config.config/3
                (elixir) lib/agent/server.ex:8: Agent.Server.init/1
                (stdlib) gen_server.erl:365: :gen_server.init_it/2
                (stdlib) gen_server.erl:333: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by stephenmoloney** [comment]
Can you create an issue for that in Openstex.Adapters.Ovh.

Seems like an issue either getting the account_temp_url - or perhaps a timeout to the server. 

Or perhaps, a connection issue.

The error is bubbling up from `:hackney`

```
Hackney encountered an error while attempting to communicate with\nthe server. The reason given was:\n\nclosed\n
```
